return {
    nincada = true,
    darkrai = true,
    heatran = true,
    helioptile = true,
    minior = true,
    meltan = true,
    stonjourner = true,
    lechonk = true,
    duraludon = true,
    nacli = true,
    shroodle = true,
    cetoddle = true,
	timerball = true,
}